package dev.kindling.processor

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.*

/**
 * KSP compiler symbol processor that scans functions annotated with [@KWidget]
 * and generates both the runtime rendering map and catalog metadata declarations.
 *
 * @property codeGenerator Generator utility for writing target source files.
 * @property logger System logging diagnostic handler.
 */
class KWidgetProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation("dev.kindling.core.components.dashboard.KWidget")
        val annotatedFunctions = symbols.filterIsInstance<KSFunctionDeclaration>().toList()

        if (annotatedFunctions.isNotEmpty()) {
            generateRegistryFile(annotatedFunctions)
        }

        return emptyList()
    }

    private fun generateRegistryFile(functions: List<KSFunctionDeclaration>) {
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(false, *functions.mapNotNull { it.containingFile }.toTypedArray()),
            packageName = "dev.kindling.core.components.dashboard",
            fileName = "GeneratedWidgetRegistry"
        )

        file.bufferedWriter().use { writer ->
            writer.write("""
                package dev.kindling.core.components.dashboard

                import androidx.compose.runtime.Composable

                // AUTO-GENERATED BY KSP - DO NOT EDIT

                val GeneratedWidgetMap: Map<String, @Composable (KWidgetModel) -> Unit> = mapOf(
            """.trimIndent())

            functions.forEach { func ->
                val annotation = func.annotations.first { it.shortName.asString() == "KWidget" }
                val typeValue = annotation.arguments.first { it.name?.asString() == "type" }.value.toString()
                val pkg = func.packageName.asString()
                val funcName = func.simpleName.asString()
                
                writer.write("\n    \"$typeValue\" to { widget -> $pkg.$funcName(title = widget.title) },")
            }

            writer.write("\n)\n\n")

            writer.write("val GeneratedWidgetCatalog: List<KWidgetMetadata> = listOf(")
            
            functions.forEach { func ->
                val annotation = func.annotations.first { it.shortName.asString() == "KWidget" }
                val typeValue = annotation.arguments.find { it.name?.asString() == "type" }?.value.toString()
                val titleValue = annotation.arguments.find { it.name?.asString() == "title" }?.value?.toString() ?: ""
                val iconValue = annotation.arguments.find { it.name?.asString() == "icon" }?.value?.toString()
                
                val width = annotation.arguments.find { it.name?.asString() == "widthCells" }?.value ?: 1
                val height = annotation.arguments.find { it.name?.asString() == "heightCells" }?.value ?: 1
                val sizeString = "$width*$height"

                @Suppress("UNCHECKED_CAST")
                val tagsArg = annotation.arguments.find { it.name?.asString() == "tags" }?.value as? List<*>
                val tagsList = tagsArg?.joinToString(prefix = "listOf(", postfix = ")") { "\"$it\"" } ?: "emptyList()"

                writer.write("\n    KWidgetMetadata(")
                writer.write("\n        type = \"$typeValue\",")
                writer.write("\n        title = \"$titleValue\",")
                writer.write("\n        tags = $tagsList,")
                writer.write("\n        icon = ${if (iconValue.isNullOrBlank()) "null" else "\"$iconValue\""},")
                writer.write("\n        size = \"$sizeString\"")
                writer.write("\n    ),")
            }

            writer.write("\n)\n")
        }
    }
}

/**
 * Provider interface implementation for registering [KWidgetProcessor] with the KSP compiler.
 */
class KWidgetProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor {
        return KWidgetProcessor(environment.codeGenerator, environment.logger)
    }
}