import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

// Kindling documentation website: a Compose Multiplatform (Wasm) app that renders the pages generated by
// docs-gen/scripts/docgen.mjs (src/wasmJsMain/.../docs/generated) next to live Kindling components.
// Not published to Maven.
//
//   node docs-gen/scripts/docgen.mjs                          # regenerate pages from KDoc
//   ./gradlew :showcase:wasmJsBrowserDevelopmentRun           # dev server on http://localhost:8080
//   ./gradlew :showcase:wasmJsBrowserDistribution             # static site in build/dist/wasmJs/productionExecutable
plugins {
    kotlin("multiplatform")
    kotlin("plugin.compose")
    id("org.jetbrains.compose")
}

kotlin {
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName.set("showcase")
        browser {
            commonWebpackConfig {
                outputFileName = "showcase.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        wasmJsMain.dependencies {
            implementation(project(":core"))
            implementation(project(":utils"))
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3.core)
            implementation(libs.compose.material.icons.extended)
            implementation(libs.compose.ui)
            implementation(libs.compose.animation)
        }
    }
}
